replicaCount: 1

image:
  repository: mooyoungacr.azurecr.io/test-app  # ACR 이미지 저장소로 변경
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-secret # ACR 인증을 위한 시크릿 추가

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 3000  # Node.js 앱에서 사용하는 포트

ingress:
  enabled: false

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: 3000  # 앱이 띄운 포트와 맞춰야 함

readinessProbe:
  httpGet:
    path: /
    port: 3000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}
