# yaml-language-server: $schema=https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/master/service-schema.json

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Docker Hub 서비스 커넥션 이름을 반영합니다.
  dockerRegistryServiceConnection: mooyoungkim-docker-hub

steps:
- task: Docker@2
  displayName: Build and push Docker image
  inputs:
    command: buildAndPush
    repository: 'dev-acr/test-app' # ACR 이름을 이미지 경로에 포함합니다.
    dockerfile: '**/Dockerfile'
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: latest

- task: HelmInstaller@1
  displayName: Install Helm
  inputs:
    helmVersionToInstall: 'latest'

- task: HelmDeploy@0
  displayName: Deploy to AKS
  inputs:
    connectionType: 'Azure Resource Manager'
    # Azure 구독 서비스 커넥션 이름을 반영합니다.
    azureSubscription: 'dev-aks-subscription'
    azureResourceGroup: 'DEV-AKS-RG'
    kubernetesCluster: 'dev-ci-cd-aks'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: 'test-app/test-app'
    releaseName: 'test-app'
    overrideValues: |
      image.repository=dev-acr/test-app
      image.tag=latest