# yaml-language-server: $schema=https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/master/service-schema.json

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  # DockerHub 또는 Azure Container Registry Service Connection 이름
  dockerRegistryServiceConnection: 'DockerHub' 
  # 실제 사용할 이미지 이름
  imageName: 'dev-acr/test-app' # ACR 기준
  # 만약 DockerHub 사용 시: 'mooyoungkim-docker-hub/test-app'

steps:
# Docker 빌드 & 푸시
- task: Docker@2
  displayName: Build and push Docker image
  inputs:
    command: buildAndPush
    repository: $(imageName)
    dockerfile: '**/Dockerfile'
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: latest

# Helm 설치
- task: HelmInstaller@1
  displayName: Install Helm
  inputs:
    helmVersionToInstall: 'latest'

# AKS 배포
- task: HelmDeploy@0
  displayName: Deploy to AKS
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'dev-aks-subscription'
    azureResourceGroup: 'DEV-AKS-RG'
    kubernetesCluster: 'dev-ci-cd-aks'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: 'test-app/test-app'
    releaseName: 'test-app'
    overrideValues: |
      image.repository=$(imageName)
      image.tag=latest
