apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: mooyoungacr.azurecr.io/test-app:1.0.5
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: acr-secret
